#!/usr/bin/env node
/**
 * Local helper for ClinicSys staff sign-in config.
 *
 *   npm run auth:hash -- "<password>"   print a password hash for STAFF_ACCOUNTS
 *   npm run auth:demo                   write .env.local with a random demo login
 *   npm run auth:demo -- --force        overwrite an existing .env.local
 *
 * The hash format must stay identical to src/lib/auth/passwordHash.ts
 * (a unit test checks they agree).
 */
import { randomBytes, scryptSync } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";

function hashPassword(password) {
  const salt = randomBytes(16);
  const hash = scryptSync(password, salt, 32);
  return `scrypt.${salt.toString("base64url")}.${hash.toString("base64url")}`;
}

const [command, ...args] = process.argv.slice(2);

if (command === "hash") {
  const password = args[0];
  if (!password) {
    console.error('Usage: npm run auth:hash -- "<password>"');
    process.exit(1);
  }
  console.log(hashPassword(password));
} else if (command === "demo") {
  const target = ".env.local";
  if (existsSync(target) && !args.includes("--force")) {
    console.error(`${target} already exists. Re-run with --force to overwrite it.`);
    process.exit(1);
  }
  const email = "frontdesk@clinic.local";
  const password = randomBytes(9).toString("base64url");
  const accounts = [{ email, name: "Front Desk Demo", title: "Front desk", passwordHash: hashPassword(password) }];
  writeFileSync(
    target,
    `# Generated by npm run auth:demo — local demo login only. Not committed.\n` +
      `AUTH_SECRET=${randomBytes(32).toString("base64url")}\n` +
      `STAFF_ACCOUNTS='${JSON.stringify(accounts)}'\n`,
  );
  console.log(`Wrote ${target}. Restart the dev server, then sign in at /login with:\n  email:    ${email}\n  password: ${password}`);
} else {
  console.error("Usage: node scripts/auth.mjs <hash|demo>");
  process.exit(1);
}
